# Generated by Django 6.1.1 on 2026-09-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=300)),
                ('enrolled_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
